WebApplication1/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class UserViewModel
    {
        public string ProfileLink { get; set; }

        public string Email { get; set; }

        public string UserName { get; set; }

        public string Rank { get; set; }

        public string Description { get; set; }

        public List<ContestCardModel> Contests { get; set; }
        public List<PhotoModel> Photos { get; set; }


    }
}

WebApplication1/Controllers/HomeSignInController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PhotoContest.Data;
using PhotoContest.Data.Models;
using PhotoContestServicess.ServiceContracts;
using PhotoContestServicess.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Loader;
using System.Threading.Tasks;
using WebApplication1.Models;
using WebApplication1.Models.CardsModels;
using WebApplication1.Models.LoggedModels;
using X.PagedList;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "User")]
    public class HomeSignInController : Controller
    {
        const string address = "https://photocontest.blob.core.windows.net/youtubedemo/";

        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly IPhotoService _photoService;
        private readonly IContestService _contestService;
        private readonly IMapper _mapper;
        private readonly ICategoryService _categoryService;
        private readonly PhotoContestContext _context;
        private readonly IUsersServices _usersServices;
        private readonly ILogger _logger;


        public HomeSignInController(UserManager<User> userManager,
            SignInManager<User> signInManager,
            IPhotoService service, IContestService service1,
            IMapper mapper, ICategoryService categoryService,
            PhotoContestContext context, IUsersServices usersServices,
            ILogger<HomeSignInController> logger)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _photoService = service;
            _contestService = service1;
            _mapper = mapper;
            _categoryService = categoryService;
            _context = context;
            _usersServices = usersServices;
            _logger = logger;
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> Index()
        {
            var getUser = await _userManager.GetUserAsync(User);

            if (getUser.RankId == 3 || getUser.RankId == 4)
            {
                ViewData["Rank"] = "ent";
            }
            else
            {
                ViewData["Rank"] = "amt";
            }
            var contests = await _contestService.GetAllContests();

            if (getUser.Contests.Count() != 0)
            {
                contests = await _contestService.GetUserContests(getUser.Id);
            }

            var photoWinners = await _photoService.GetPhotosWinners();

            var cont = _mapper.Map<List<Contest>, List<ContestCardModel>>(contests);
            var photos = _mapper.Map<List<Photo>, List<PhotoModel>>(photoWinners);

            var indexLoggedModel = new IndexModelLogged() { ContestCardModels = cont, PhotoCardModels = photos };

            _logger.LogInformation("Home page created.");

            return View("Index", indexLoggedModel);

        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> UserContestsSearchAsync(string id, IFormCollection col, int? page)
        {
            var getUser = await _userManager.GetUserAsync(User);
            var categories = _categoryService.GettAll();
            ViewData["catname"] = categories;

            if (getUser.RankId == 3 || getUser.RankId == 4)
            {
                ViewData["Rank"] = "ent";
            }

            else
            {
                ViewData["Rank"] = "amt";
            }

            if (id == "usercont")
            {
                var search = col["search"][0].ToString();

                var contusers = await _contestService.ContestCategory(1, getUser.Id);
                var cot = _mapper.Map<List<Contest>, List<ContestCardModel>>(contusers.Where(c => c.Name.Contains(search)).ToList());

                var pageNumber = page ?? 1;
                int pageSize = 3;
                var onePageOfContests = cot.ToPagedList(pageNumber, pageSize);
                var indexLoggedModel = new UserContestFilterModel() { CardsModels = onePageOfContests };
                ViewData["numOfCont"] = "user";

                _logger.LogInformation("User contest search created.");

                return View("UserContestsFilter", indexLoggedModel);
            }

            else
            {
                var search = col["search"][0].ToString();

                var contusers = await _contestService.GetAllContests();
                var cot = _mapper.Map<List<Contest>, List<ContestCardModel>>(contusers.Where(c => c.Name.Contains(search)).ToList());

                var pageNumber = page ?? 1;
                int pageSize = 3;
                var onePageOfContests = cot.ToPagedList(pageNumber, pageSize);
                var indexLoggedModel = new UserContestFilterModel() { CardsModels = onePageOfContests };
                ViewData["numofcont"] = "all";

                return View("UserContestsFilter", indexLoggedModel);
            }

        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> UserContestsAsync(string id, int? page)
        {
            var getUser = await _userManager.GetUserAsync(User);
            var categories = _categoryService.GettAll();
            ViewData["catname"] = categories;

            if (getUser.RankId == 3 || getUser.RankId == 4)
            {
                ViewData["Rank"] = "ent";
            }

            else
            {
                ViewData["Rank"] = "amt";
            }

            if (id == "usercont")
            {
                var contusers = await _contestService.GetUserContests(getUser.Id);
                var cot = _mapper.Map<List<Contest>, List<ContestCardModel>>(contusers);

                var pageNumber = page ?? 1;
                int pageSize = 3;
                var onePageOfContests = cot.ToPagedList(pageNumber, pageSize);
                var indexLoggedModel = new UserContestFilterModel() { CardsModels = onePageOfContests };
                ViewData["numOfCont"] = "user";

                return View("UserContestsFilter", indexLoggedModel);
            }

            else
            {
                var contusers = await _contestService.GetAllContests();
                var cot = _mapper.Map<List<Contest>, List<ContestCardModel>>(contusers);

                var pageNumber = page ?? 1;
                int pageSize = 3;
                var onePageOfContests = cot.ToPagedList(pageNumber, pageSize);
                var indexLoggedModel = new UserContestFilterModel() { CardsModels = onePageOfContests };
                ViewData["numofcont"] = "all";

                return View("UserContestsFilter", indexLoggedModel);
            }
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> UserContFilterAsync(IFormCollection collection, int? page, string id)
        {
            var getUser = await _userManager.GetUserAsync(User);
            var categories = _categoryService.GettAll();
            ViewData["catname"] = categories;
            var catId = 0;

            if (getUser.RankId == 3 || getUser.RankId == 4)
            {
                ViewData["Rank"] = "ent";
            }
            else
            {
                ViewData["Rank"] = "amt";
            }

            string catname = string.Empty;

            if (collection.ContainsKey("radioNoLabel"))
            {
                catname = collection["radioNoLabel"];
                catId = await _categoryService.GetCategoryid(catname);
            }

            var phaselist = new List<int>();

            for (int i = 1; i <= 3; i++)
            {
                if (collection.ContainsKey(i.ToString()))
                {
                    phaselist.Add(i);

                }
            }

            var contcard = new List<Contest>();

            if (id == "all")
            {
                contcard = await _contestService.GetAllContestsFilter(catId, phaselist);
                ViewData["numofcont"] = id;
            }

            if (id == "user")
            {
                contcard = await _contestService.ContestCatUserPhase(catId, getUser.Id, phaselist);
                ViewData["numofcont"] = id;
            }

            var contescards = _mapper.Map<List<Contest>, List<ContestCardModel>>(contcard);

            var pageNumber = page ?? 1;
            int pageSize = 3;
            var onePageOfContests = contescards.ToPagedList(pageNumber, pageSize);
            var indexLoggedModel = new UserContestFilterModel() { CardsModels = onePageOfContests };

            return View("UserContestsFilter", indexLoggedModel);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> ContestsInsideAsync(string id, int? page)
        {
            var getUser = await _userManager.GetUserAsync(User);
            var cont = await _contestService.GetContest(id);

            var checkJoined = await _usersServices.CheckIfUserJoinedContest(getUser.Id, cont.Id);
            var category = await _categoryService.GetCategoryname(cont.CategoryId);

            var photomodels = _mapper.Map<List<PhotoScoreContest>, List<PhotoModel>>(_contestService.GetContestPhotos(id));
            var contescard = _mapper.Map<Contest, ContestCardModel>(cont);

            contescard.Category = category;
            contescard.PhotosCount = photomodels.Count();

            if (getUser.RankId == 3 || getUser.RankId == 4)
            {
                ViewData["Rank"] = "ent";
                bool rated = await _usersServices.CheckIfUserRatedContest(getUser.Id, cont.Id);
                contescard.Rated = rated;
            }
            else
            {
                ViewData["Rank"] = "amt";
                contescard.Rated = false;
            }

            if (checkJoined == true)

WebApplication1/Views/Shared/ApiKey.cshtml
    <div>
        <partial name="NavBarUpdated" />

    </div>
<br />

<div>
    <h1>
        Your API key is:
        <br />
    </h1>
    <h2>
        @ViewData["apikey"].ToString()
    </h2>
</div>

WebApplication1/Views/Shared/LoadMoreViewSigned.cshtml
@model IndexModelLogged


<div class="container" style="border-bottom:solid; text-align:center; width:800px; position:relative; left:0px">
    <header class="accordion-header mb-1" style="font-size:xx-large; color:lightsteelblue"><i>Check our newest Contests</i></header>
</div>
<br />
<br />
<div class="interior container clearfix" style="border:none; ">

    <div class="row">
        @{
            for (int i = 0; i < 3; i++)
            {
                <div class="col-xs-12 col-sm-6 col-md-4 blogBox moreBox">
                    <div class="card">
                                <div class="card-header p-0 mx-3 mt-3 position-relative z-index-1">
                                    @if (User.IsInRole("User"))
                                    {
                                        <a asp-action="ContestsInside" asp-controller="HomeSignIn" asp-route-id="@Model.ContestCardModels[i].Name" class="d-block">
                                            <img src="@Model.ContestCardModels[i].Profile" class="img-fluid border-radius-lg" style="height:200px; width:320px">
                                        </a>
                                    }
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <a asp-action="ContestsInside" asp-controller="Admin" asp-route-id="@Model.ContestCardModels[i].Name" class="d-block">
                                            <img src="@Model.ContestCardModels[i].Profile" class="img-fluid border-radius-lg" style="height:200px; width:320px">
                                        </a>
                                    }

                                </div>


                                <div class="card-body m-n3">


                                    <p class="card-description mb-1">
                                        @Model.ContestCardModels[i].Description
                                    </p>

                                    @if (User.IsInRole("User"))
                                    {
                                        <a asp-action="ContestsInside" asp-controller="HomeSignIn" asp-route-id="@Model.ContestCardModels[i].Name" class="text-info icon-move-right ">
                                            Read More
                                            <i class="fas fa-arrow-right text-sm" aria-hidden="true"></i>
                                        </a>
                                    }
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <a asp-action="ContestsInside" asp-controller="Admin" asp-route-id="@Model.ContestCardModels[i].Name" class="text-info icon-move-right ">
                                            Read More
                                            <i class="fas fa-arrow-right text-sm" aria-hidden="true"></i>
                                        </a>
                                    }
                                    <div class="author align-items-center">
                                    </div>
                                </div>
                    </div>
                    <div class="shadow p-3 mb-5 bg-light rounded" style="height:40px; width:170px; z-index:999;  position:relative; top:-112px; left:163px; opacity:0.8">Join till: @Model.ContestCardModels[i].EndDate.Subtract(TimeSpan.FromDays(1)).ToShortDateString()</div>
                </div>
            }

        }

        @{
            for (int i = 3; i < Model.ContestCardModels.Count(); i++)
            {
                <div class="col-xs-12 col-sm-6 col-md-4 blogBox moreBox" style="display: none;">
                    <div class="card">
                        <div class="card-header p-0 mx-3 mt-3 position-relative z-index-1">
                            @if (User.IsInRole("User"))
                            {
                                <a asp-action="ContestsInside" asp-controller="HomeSignIn" asp-route-id="@Model.ContestCardModels[i].Name" class="d-block">
                                    <img src="@Model.ContestCardModels[i].Profile" class="img-fluid border-radius-lg" style="height:200px; width:320px">
                                </a>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <a asp-action="ContestsInside" asp-controller="Admin" asp-route-id="@Model.ContestCardModels[i].Name" class="d-block">
                                    <img src="@Model.ContestCardModels[i].Profile" class="img-fluid border-radius-lg" style="height:200px; width:320px">
                                </a>
                            }

                        </div>

                        <div class="card-body m-n3">

                            <p class="card-description mb-1">
                                @Model.ContestCardModels[i].Description
                            </p>
                            @if (User.IsInRole("User"))
                            {
                                <a asp-action="ContestsInside" asp-controller="HomeSignIn" asp-route-id="@Model.ContestCardModels[i].Name" class="text-info icon-move-right ">
                                    Read More
                                    <i class="fas fa-arrow-right text-sm" aria-hidden="true"></i>
                                </a>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <a asp-action="ContestsInside" asp-controller="Admin" asp-route-id="@Model.ContestCardModels[i].Name" class="text-info icon-move-right ">
                                    Read More
                                    <i class="fas fa-arrow-right text-sm" aria-hidden="true"></i>
                                </a>
                            }
                            <div class="author align-items-center">
                            </div>
                        </div>
                    </div>
                    <div class="shadow p-3 mb-5 bg-light rounded" style="height:40px; width:170px; z-index:999;  position:relative; top:-112px; left:163px; opacity:0.8">Join till: @Model.ContestCardModels[i].EndDate.Subtract(TimeSpan.FromDays(1)).ToShortDateString()</div>
                </div>
            }
        }

        <div id="loadMore" style="position:relative; top:-100px">
            <a href="#">Load More</a>
        </div>

    </div>
</div>

WebApplication1/Views/Shared/NavBarUpdated.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<PhotoContest.Data.Models.User> Signinmanager
@inject Microsoft.AspNetCore.Identity.UserManager<PhotoContest.Data.Models.User> UserManger

<nav class="navbar navbar-expand-lg  blur blur-rounded top-0 border-bottom z-index-3 shadow w-100 mt-4 d-none d-lg-block my-3 py-2">
    <div class="container-fluid">

        @if (User.IsInRole("Admin"))
        {
            <a class="navbar-brand font-weight-bolder ms-3" asp-action="Index" asp-controller="Admin" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom" target="_blank">
                PhotoContest
            </a>
        }
        else
        {
            <a class="navbar-brand font-weight-bolder ms-3" asp-action="Index" asp-controller="HomeSignIn" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom" target="_blank">
                PhotoContest
            </a>
        }

        <ul class="dropdown" style="position:relative; left:-500px; top:7px;">
            <button class="btn btn dropdown-toggle"
                    type="button" id="dropdownMenu1" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                Contests
            </button>




            @if (User.IsInRole("Admin"))
            {
                <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <a class="dropdown-item" asp-action="UserContests" asp-controller="Admin" asp-route-id="usercont">Your Contests</a>
                    <a class="dropdown-item" asp-action="UserContests" asp-controller="Admin" asp-route-id="allcont">All Contests</a>
                </div>
            }

            @if (User.IsInRole("User"))
            {
                <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <a class="dropdown-item" asp-action="UserContests" asp-controller="HomeSignIn" asp-route-id="usercont">Your Contests</a>
                    <a class="dropdown-item" asp-action="UserContests" asp-controller="HomeSignIn" asp-route-id="allcont">All Contests</a>
                </div>
            }
        </ul>



        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav navbar-nav-hover mx-auto">

                <div class="container-fluid">
                    <ul class="dropdown" style="position:relative; left:-500px; top:7px;">
                        <button class="btn btn dropdown-toggle"
                                type="button" id="dropdownMenu1" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            Contests
                        </button>




                        @if (User.IsInRole("Admin"))
                        {
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <a class="dropdown-item" asp-action="UserContests" asp-controller="Admin" asp-route-id="usercont">Your Contests</a>
                                <a class="dropdown-item" asp-action="UserContests" asp-controller="Admin" asp-route-id="allcont">All Contests</a>
                            </div>
                        }
                        else
                        {
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <a class="dropdown-item" asp-action="UserContests" asp-controller="HomeSignIn" asp-route-id="usercont">Your Contests</a>
                                <a class="dropdown-item" asp-action="UserContests" asp-controller="HomeSignIn" asp-route-id="allcont">All Contests</a>
                            </div>
                        }
                    </ul>
                </div>
                @if (User.IsInRole("Admin"))
                {
                    <li style="position:relative; left:-480px; top:7px;">
                        <a type="button" class="btn btn-outline-info" asp-controller="Admin" asp-action="GetUsers" style="height:33px; width:70px; border:none">Users </a>
                    </li>
                }
                else
                {
                    <li style="position:relative; left:-480px; top:7px;">
                        <a type="button" class="btn btn-outline-info" asp-controller="HomeSignIn" asp-action="GetUsers" style="height:33px; width:70px; border:none">Users </a>
                    </li>
                }


                @if (User.IsInRole("Admin"))
                {

                    <li style="position:relative; left:-460px; top:7px;">
                        <a type="button" class="btn btn-outline-info" asp-action="ExplorePhotos" asp-controller="Admin" style="height:33px; width:70px; border:none">Photos </a>
                    </li>
                }
                else
                {
                    <li style="position:relative; left:-460px; top:7px;">
                        <a type="button" class="btn btn-outline-info" asp-action="ExplorePhotos" asp-controller="HomeSignIn" style="height:33px; width:70px; border:none">Photos</a>
                    </li>
                }

                @if (User.IsInRole("User"))
                {
                    @if ((string)ViewData["Rank"] == "ent")
                    {
                        <li style="position:relative; left:-430px; top:7px;">
                            <a type="button" class="btn btn-outline-info" asp-action="UserContests" asp-controller="HomeSignIn" asp-route-id="All" style="height:33px; width:70px; border:none">Appraise</a>
                        </li>
                    }
                }

                @if (User.IsInRole("Admin"))
                {
                    <li style="position:relative; left:-430px; top:7px;">
                        <a type="button" class="btn btn-outline-info" style="height:33px; width:170px; border:none" asp-action="ManageContests" asp-controller="Admin">Manage Contests</a>
                    </li>
                }


            </ul>

            @if (User.IsInRole("User"))
            {
                <ul class="navbar-nav" style="position:absolute; z-index:999; top:21px; right:300px">
                    <!-- Button trigger modal -->
                    <li>
                        <a type="button" class="btn btn-outline-primary" asp-action="GetUserApiKey" asp-controller="HomeSignIn" asp-route-id="@User.Identity.Name" style="border:none">
                            <strong> Get API key</strong>
                        </a>
                    </li>
                </ul>
            }
            @if (User.IsInRole("Admin"))
            {
                <ul class="navbar-nav" style="position:absolute; z-index:999; top:21px; right:300px">
                    <!-- Button trigger modal -->
                    <li>
                        <a type="button" class="btn btn-outline-primary" asp-action="GetUserApiKey" asp-controller="ADmin" asp-route-id="@User.Identity.Name" style="border:none">
                            <strong> Get API key</strong>
                        </a>
                    </li>
                </ul>
            }


            <ul class="navbar-nav" style="position:absolute; z-index:999; top:21px; right:200px">
                <!-- Button trigger modal -->
                @if (User.IsInRole("Admin"))
                {
                    <li>
                        <a type="button" class="btn btn-outline-primary" asp-action="UserDetails" asp-controller="Admin" style="border:none">
                            <strong> Profile </strong>
                        </a>
                    </li>
                }
                @if (User.IsInRole("User"))
                {
                    <li>
                        <a type="button" class="btn btn-outline-primary" asp-action="UserDetails" asp-controller="HomeSignIn" style="border:none">
                            <strong> Profile </strong>
                        </a>
                    </li>
                }

            </ul>

            @if (User.IsInRole("User"))
            {
                <ul class="navbar-nav" style="position:absolute; z-index:999; top:21px; right:100px">
                    <!-- Button trigger modal -->
                    <li>
                        <a type="button" class="btn btn-outline-primary" asp-action="Logout" asp-controller="HomeSignIn" style="border:none">
                            <strong> Logout</strong>
                        </a>
                    </li>
                </ul>
            }

            @if (User.IsInRole("Admin"))
            {
                <ul class="navbar-nav" style="position:absolute; z-index:999; top:21px; right:100px">
                    <!-- Button trigger modal -->
                    <li>
                        <a type="button" class="btn btn-outline-primary" asp-action="Logout" asp-controller="Admin" style="border:none">
                            <strong> Logout</strong>
                        </a>
                    </li>
                </ul>
            }

            <ul class="navbar-nav" style="position: relative; top:8px">
                @if (User.IsInRole("User"))
                {
                    <a class="btn btn-icon btn-2 btn-primary" asp-action="AboutUs" asp-controller="HomeSignIn">
                        <span class="btn-inner--icon"><i class="ni ni-bulb-61"></i></span>
                    </a>
                }
                @if (User.IsInRole("Admin"))
                {
                    <a class="btn btn-icon btn-2 btn-primary" asp-action="AboutUs" asp-controller="Admin">
                        <span class="btn-inner--icon"><i class="ni ni-bulb-61"></i></span>
                    </a>
                }
            </ul>
        </div>
    </div>
</nav>

WebApplication1/Views/Shared/UpdateUser.cshtml
@model UserViewModel


    <div>
        <partial name="NavBarUpdated" />
    </div>

    <div class="container">

        <div class="card" style="text-align:center; border:none; width:800px; position:relative; left:150px; top:60px;">
            <header class="accordion-header mb-1" style="font-size:xx-large; color:lightsteelblue"><i>Update Profile</i></header>
        </div>

        <form asp-controller="HomeSignIn" asp-action="EditUserProfile" method="post" enctype="multipart/form-data" style="border:none;  width:700px; position:relative; top:150px; left:210px;  opacity:0.8;">
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Username</label>
                <div class="col-8">

                    <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.UserName">
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Rank</label>
                <div class="col-8">

                    <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.Rank">
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
                <div class="col-8">

                    <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="@Model.Email">
                </div>
            </div>
            <div class="form-group row">
                <label for="text3" class="col-4 col-form-label">Update description </label>
                <div class="col-8">
                    <textarea asp-for="@Model.Description" class="form-control" style="width:435px;"></textarea>
                </div>
            </div>

            <label for="text5" class="col-4 col-form-label" style="position:relative; left:-20px;">Upload Cover Photo</label>
            <div class="col-8">
                <input type="file" name="file" class="form-control" style="position:relative; left:-15px">

            </div>
            <div class="form-group row">

                <div class="form-group row" style="position:relative; top:23px; left:60px;
">
                    <div class="offset-4 col-8">
                        <button name="submit" type="submit" class="btn btn-info">Submit</button>
                    </div>
                </div>

            </div>
        </form>
    </div>